#!/bin/sh
unset IFS
set -euf

DEFAULT_TASK='lint'

audit() {
    snyk
}

lint() {
    bashate
    funk
    shellcheck
    shfmt
    slick
}

bashate() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 .venv/bin/bashate -i E006
}

funk() {
    command funk .
}

shellcheck() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 shellcheck
}

shfmt() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 shfmt -w -i 4
}

slick() {
    stank -print0 -sh . |
        xargs -0 -n 1 slick
}

snyk() {
    command snyk test --all-projects --exclude=requirements.txt
    command snyk test --command=.venv/bin/python3
}

if [ "$#" -eq 0 ]; then
    "$DEFAULT_TASK"
    exit
fi

for ARG in "$@"; do
    "$ARG"
done
