#!/bin/bash
unset IFS
set -eufo pipefail

VERSION="$(nile -v)"

audit() {
    govulncheck
}

bashate() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 .venv/bin/bashate -i E006
}

docker_build() {
	tuggy -t "n4jm4/nile:$VERSION" --load
}

docker_push() {
	tuggy -t "n4jm4/nile:$VERSION" -a n4jm4/nile --push
}

docker_test() {
	tuggy -t n4jm4/nile:test --load
	tuggy -t n4jm4/nile:test --push
}

funk() {
    command funk .
}

govulncheck() {
    command govulncheck -scan package ./...
}

lint() {
    bashate
    funk
    shellcheck
    shfmt
    slick
}

shellcheck() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 shellcheck
}

shfmt() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 shfmt -w -i 4
}

slick() {
    stank -print0 -sh . |
        xargs -0 -n 1 slick
}

unit_test() {
    nile -v
    nile -h
}

TASKS=' \
    audit \
    bashate \
	docker_build \
	docker_push \
	docker_test \
    funk \
    govulncheck \
    lint \
    shellcheck \
    shfmt \
    slick \
    unit_test'

SELECTED_TASKS='unit_test'

if [ "$#" -gt 0 ]; then
    SELECTED_TASKS="$*"
fi

for TASK in $SELECTED_TASKS; do
    case "$TASKS" in
    *"$TASK"*)
        "$TASK"
        ;;
    *)
        echo "error: no such task: $TASK"
        exit 1
        ;;
    esac
done
